### ISSUE TITLE
Support TTL in records

### ISSUE THREAD

**Issue by ManuelB** [nic-at/rc0go#1]
Hi,
it currently seams that the client does not support TTL.

Can it be added?

Thanks a lot
    Manuel

**Comment by ManuelB** [comment]
https://github.com/kubernetes-incubator/external-dns/pull/1221

**Comment by MikeAT** [comment]
Hi, 

I just release v1.1.1 with support for custom TTLs per RRsets. 

Best,
Michael

**Comment by ManuelB** [comment]
Cool!
